version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./db-init-script.sql:/var/opt/mssql/db-init-script.sql
    command: >
      /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -d master -i /var/opt/mssql/db-init-script.sql && wait"


  web:
    image: web-shop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=HireMeDB;User=sa;Password=YourStrong!Passw0rd;"

volumes:
  sql_data:
